# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: acd10996abc08f92df61477f7ea198802f0311661db8e192cfb5df572dee04065222dadf25c5797885e4f678e9cacada3e93f399212c05002fc218ff8e455d8a

test:
  secret_key_base: b719cbe2c5ee749a11420fb8e67d0b3fab007e23a4cd31a267074da9a272037699817f7aa7d83325f8dea9f6371b3bec975ff85a600e712d7a0eae48a01b71b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
